[build]
builder = "NIXPACKS"

[[services]]
name = "vinylbe"
startCommand = "python start_services.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services.environmentVariables]]
name = "PORT"
value = "5000"
